### ISSUE TITLE
Duplicate transactions are not imported

### ISSUE THREAD

**Issue by ryenbeatty** [schurig/ynab-bank-importer#22]
Hi there,

First of all, thank you for this project, I have been looking for this for a while! I have everything up and running using the fints importer (ING DiBA), and have noticed that when I have 2 transactions from the same vendor, with the same monetary value, that only one will be imported.

I'm more than happy to jump into the code if you can give me some direction.

Thanks!

**Comment by schurig** [comment]
Hi @ryenbeatty, I just fund out that the FinTS protocol doesn't return any time information in the `date` attribute and for now I don't see what could be a good way to get an uniq attribute of the transaction to prevent this problem from happening **and and the same time** to prevent duplicate entries from happening in case a field changes from time to time (because of processing).

This is the current way how I generate the `import_id` https://github.com/schurig/ynab-bank-importer/blob/master/lib/dumper/fints.rb#L67-L77

How comfortable do you feel with ruby? Because what would help would be to get the information that the FinTS api returns for both of the transactions to see what is different. You can get this doing this for example:

```diff
diff --git i/lib/dumper/fints.rb w/lib/dumper/fints.rb
index 860ae22..6fa8b0f 100644
--- i/lib/dumper/fints.rb
+++ w/lib/dumper/fints.rb
@@ -22,6 +22,7 @@ class Dumper
       statement = client.get_statement(account, Date.today - 35, Date.today)

       statement.map { |t| to_ynab_transaction(t) }
+      exit
     end

     private
@@ -31,6 +32,9 @@ class Dumper
     end

     def date(transaction)
+      puts transaction.inspect
+      puts
+      puts
       transaction.entry_date
     end

```

and then [run the script](https://github.com/schurig/ynab-bank-importer/wiki/Raspberry-PI-without-docker#run-the-script).

This will run the script but only fetch the transactions and print them out in your console.

I would recommend to temporary comment out all entries in the `config.yml` except the ing0diba one (in case you have multiple).
